comment: Config for LoLA from Figure 3 of https://arxiv.org/pdf/1812.10659 (OpenFHE backend)

ckks_params:
  LogN: 14
  LogQ: [29, 26, 26, 26, 26, 26]
  LogP: [29, 29]
  LogScale: 26
  H: 8192
  RingType: ConjugateInvariant

orion:
  margin: 2 # >= 1
  embedding_method: hybrid # [hybrid, square]
  backend: openfhe # [lattigo, openfhe, heaan]

  fuse_modules: true
  debug: false

  diags_path: ../data/diagonals.h5 # "path/to/diags" | ""
  keys_path: ../data/keys.h5 # "path/to/keys" | ""
  io_mode: none # "load" | "save" | "none"